apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379 

    # this creates redis:6379 Accessible from API and  Worker
    #WITHOUT SERVICE  No communication Redis unreachable